---
title: "model_gbm"
author: "Yash Karandikar"
date: "7/20/2020"
output: html_document
---

## set working directory + echo commands
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:\\Users\\veena\\Desktop\\ophthalmology\\csv')
knitr::opts_chunk$set(echo = TRUE)
```

## df cleanup from ophcitation-analysis01-penalizedregression.Rmd
```{r}
library(tidyverse)
df_scopus_csv <-select(df_scopus_csv, -index, -authorlist, -authoridlist, -access.type)
df_scopus_csv <-filter(df_scopus_csv, !is.na(tc))

quantile(df_scopus_csv$tc, c(0.75)) # 20
df_scopus_csv$tcB<-ifelse(df_scopus_csv$tc>=20, 1, 0)

colnames(df_scopus_csv)[colSums(is.na(df_scopus_csv)) > 0]

df_scopus_csv$pagecount=replace_na(df_scopus_csv$pagecount, 1)
df_scopus_csv[is.na(df_scopus_csv)] = 0

df_train<-filter(df_scopus_csv, split==0)
df_dev<-filter(df_scopus_csv,split==1)
df_test <- filter(df_scopus_csv, split==2)
```

## gbm train model
```{r}
library(gbm)

LogLossBinary = function(actual, predicted, eps = 1e-15) {  
  predicted = pmin(pmax(predicted, eps), 1-eps)  
  - (sum(actual * log(predicted) + (1 - actual) * log(1 - predicted))) / length(actual)
}

# gbm source
# https://www.datatechnotes.com/2018/03/classification-with-gradient-boosting.html

library(caret)
library(e1071)
library(pROC)
library(precrec)

# define number of trees - keep consistent with train and dev/test
num_trees_var <- 300

# no need to further tune the hyperparameters - the optimal values from the grid are in the model below

# use caret_gbm_fit final values to create the optimal train gbm model
# varImp is also no longer needed, since the "hyperpredictors" like Unnamed..0_* are gone
optimal_gbm_train_model <- gbm(tcB ~ ., 
                               data=select(df_train, -tc, -split, -pagecount, -X, -Unnamed..0_y, -Unnamed..0_x, -year),
                               distribution = "bernoulli",
                               n.trees = 300,
                               shrinkage = 0.031,
                               n.minobsinnode = 10,
                               interaction.depth = 4,
                               cv.folds = 10)

print(optimal_gbm_train_model)
```

## test model + evaluation metrics
```{r}
# functional approach to dev and test set
test_preds_with_gbm <- function(gbm_data, num_trees) {
  cv.gbm_predictions <- predict.gbm(object = optimal_gbm_train_model,
                                    newdata = gbm_data,
                                    n.trees = num_trees,
                                    type = 'response')
  
  print(LogLossBinary(gbm_data$tcB, cv.gbm_predictions))
  print(data.frame('Actual' = gbm_data$tcB, 'Predicted' = cv.gbm_predictions))
  
  best_tree_for_prediction <- gbm.perf(optimal_gbm_train_model, method='cv')
  print(best_tree_for_prediction)
  summary(optimal_gbm_train_model)
  
  cv.ifelse_preds <- ifelse(cv.gbm_predictions > quantile(cv.gbm_predictions, c(0.75)), 1, 0)
  
  print(table(gbm_data$tcB))
  print(table(cv.ifelse_preds))
  
  roc_graph <- roc(gbm_data$tcB, cv.gbm_predictions,
                   ci=TRUE, ci.alpha=0.95, plot=TRUE,
                   print.auc=TRUE, legacy.axes=TRUE)
  
  sens.ci <- ci.se(roc_graph)
  plot(sens.ci, type="shape", col="lightblue")
  
  auc_val <- pROC::auc(roc_graph)
  print(auc_val)
  
  precrec_obj <- precrec::evalmod(scores = cv.gbm_predictions, labels = gbm_data$tcB)
  autoplot(precrec_obj) 
}

test_preds_with_gbm(df_test, num_trees_var)
```
